#!/usr/bin/env python
import sys
from pathlib import Path
sys.path.append(Path(__file__).parent.resolve())

from PyQt6.QtWidgets import QApplication
from qtwave_.MainWindow import MainWindow

if __name__ == "__main__":
	app = QApplication(sys.argv)
	window = MainWindow()
	app.exec()
