name: Github action CI

on:
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: update
      run: sudo apt update
    - uses: actions/checkout@v3
    - name: install
      run: apt update && apt install cmake libgoogle-glog-dev g++ gcc libgtest-dev
    - name: cmake
      run: |
        mkdir build;
        cd build;
        cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: cd build && make -j
    - name: unittest
      run: cd build && ctest
