name: Github action CI

on:
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cmake libgoogle-glog-dev g++ gcc libgtest-dev
        version: 1.0
    - name: install
      run: apt install
    - name: cmake
      run: |
        mkdir build;
        cd build;
        cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: cd build && make -j
    - name: unittest
      run: cd build && ctest
